### ISSUE TITLE
file upload in HydroTrend not working?

### ISSUE THREAD

**Issue by iovereem** [csdms/wmt#87]
I tried to upload different hypsometry files to HydroTrend. I have been carefull to edit these files to look precisely like the HYDRO0.HYPS file that is generated for the simulations that did run sucesfully (but with choosing one of the default files). I even tried uploading one of the files that were packaged from a previous run.

The upload button gives me a indication the file has been successfully loaded. I then save the run settings. 

If I subsequently submit the run to Beach WMT gives an error:

The URL 'https://csdms.colorado.edu/wmt/api-dev/run/stage' did not give an 'OK' response. Response code: 500

**Comment by mdpiper** [comment]
Fixed with 9659405e0eccad1b16f3068b51c895bf1ea42ce9.
