### ISSUE TITLE
make it clear how to go back to the list of models once the driver is activated

### ISSUE THREAD

**Issue by iovereem** [csdms/wmt#90]
This is a comment or question from several students during the MN lab.

Once a model / driver has been selected, they did not realize that they had to 'delete' the currently selected driver to get back to the list of components.

So their model panel looks like this and they want to 'go back'.
![screen shot 2014-08-25 at 10 32 38 am](https://cloud.githubusercontent.com/assets/7684648/4032966/c043f984-2c75-11e4-93be-a0b4334e666c.png)
 
One possible suggestion: add a small back arrow icon on the lefthand corner and do the same action as a 'delete'.

Another possible suggestion: change the wording for 'delete'? Perhaps 'remove'?

**Comment by mdpiper** [comment]
This issue was moved to csdms/wmt-client#89
